### ISSUE TITLE
Addon doesn't install at Blender 4.1.1 or latest 4.2.1

### ISSUE THREAD

**Issue by PyroGH** [ArdCarraigh/Blender_APX_Addon#5]

**Comment by ArdCarraigh** [comment]
You have to copy paste the directory called "io_mesh_apx" from the zip file to **C:\Program Files\Blender\4.2.0\4.2\scripts\addons_core** for Blender 4.2+ or **C:\Program Files\Blender\4.1.1\4.1\scripts\addons** for Blender 4.1.

**Comment by PyroGH** [comment]
Thank you! It worked for me in **C:\Users\USER_NAME\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons** for Blender 4.2.1, pasting the folder "io_mesh_apx" you mentioned, instead of the root folder from the .zip
